spring:
  application:
    name: api-gateway-zuul

server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

      #路由规则
zuul:
  routes:
    hello:
      path: /hello/**
      service-id: eureka-consumer-ribbon-hystrix
  host:
    max-per-route-connections: 600000
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000

hystrix:
 command:
  default:
   execution:
    timeout: #配置命令的执行，是否会超时
     enabled: false


ribbon:
 ReadTimeout: 20000  #读取超时时间
 onnectTimeout: 10000  #好像这个没什么用  如果说有人知道这个是什么作用可以评论告诉我一下
