spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/showlike/springcloud-demo2.git
          searchPaths: config-repo
server:
  port: 1201